# Generated by Django 5.1.6 on 2025-03-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='sem',
            field=models.IntegerField(choices=[(1, '1'), (2, '2')], null=True),
        ),
    ]
