# Generated by Django 5.1.6 on 2025-03-06 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0003_module_sem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='prof',
        ),
        migrations.RemoveField(
            model_name='module',
            name='sem',
        ),
        migrations.RemoveField(
            model_name='module',
            name='year',
        ),
        migrations.CreateModel(
            name='Module_instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('sem', models.IntegerField(choices=[(1, '1'), (2, '2')], null=True)),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rate.module')),
                ('prof', models.ManyToManyField(to='rate.professor')),
            ],
        ),
        migrations.AlterField(
            model_name='rating',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rate.module_instance'),
        ),
    ]
